import Astra_icon from './Astra_icon.png'
import Breach_icon from './Breach_icon.png'
import Brimstone_icon from './Brimstone_icon.png'
import Chamber_icon from './Chamber_icon.png'
import Clove_icon from './Clove_icon.png'
import Cypher_icon from './Cypher_icon.png'
import Deadlock_icon from './Deadlock_icon.png'
import Fade_icon from './Fade_icon.png'
import Gekko_icon from './Gekko_icon.png'
import Harbor_icon from './Harbor_icon.png'
import Iso_icon from './Iso_icon.png'
import Jett_icon from './Jett_icon.png'
import KJ_icon from './KJ_icon.png'
import KO_icon from './KO_icon.png'
import Neon_icon from './Neon_icon.png'
import Omen_icon from './Omen_icon.png'
import Phoenix_icon from './Phoenix_icon.png'
import Raze_icon from './Raze_icon.png'
import Reyna_icon from './Reyna_icon.png'
import Sage_icon from './Sage_icon.png'
import Skye_icon from './Skye_icon.png'
import Sova_icon from './Sova_icon.png'
import Viper_icon from './Viper_icon.png'
import Yoru_icon from './Yoru_icon.png'

export default index
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;
// modules.export = Yoru_icon;